server:
  port: 8082

spring:
  application:
    name: javaspringstore

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/appbd
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

app:
  jwt:
    secret: "someSecretKey"

bot:
  url: http://194.87.237.31:8087
  key: sasha