server:
  port: 8082

spring:
  application:
    name: javaspringstore
#  data:
#    redis:
#      host: localhost
#      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/appbd
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

app:
  jwt:
    secret: "someSecretKey"
#  redis:
#    enable: true