version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: application
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#  redis:
#    image: redis:7.0.12
#    ports:
#      - "6379:6379"